"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _carregar_arquivo_env(caminho: Path) -> int:
    """Carrega variáveis KEY=VALUE do arquivo .env para os.environ. Retorna quantas chaves foram lidas."""
    if not caminho.exists():
        return 0
    carregadas = 0
    with caminho.open(encoding='utf-8') as arquivo:
        for linha in arquivo:
            linha = linha.strip()
            if not linha or linha.startswith('#') or '=' not in linha:
                continue
            chave, valor = linha.split('=', 1)
            chave = chave.strip()
            valor = valor.strip().strip('"').strip("'")
            if chave:
                antes = chave not in os.environ
                os.environ.setdefault(chave, valor)
                if antes and chave in os.environ:
                    carregadas += 1
    return carregadas


_env_path = BASE_DIR / '.env'
if not _env_path.exists():
    _env_path = BASE_DIR / '.env.exemple'

_carregar_arquivo_env(_env_path)


def _env_bool(nome: str, padrao: bool = False) -> bool:
    valor = os.environ.get(nome)
    if valor is None:
        return padrao
    return valor.lower() in ('1', 'true', 'yes', 'on')


def _env_lista(nome: str, padrao: str = '') -> list:
    bruto = os.environ.get(nome)
    if not bruto:
        bruto = padrao
    return [item.strip() for item in bruto.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if _env_bool('DJANGO_DEBUG', True):
        SECRET_KEY = 'django-insecure-dev-only-defina-DJANGO_SECRET_KEY-no-env'
    else:
        raise ImproperlyConfigured(
            'Defina DJANGO_SECRET_KEY no arquivo .env (copie de .env.exemple).'
        )

DEBUG = _env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = _env_lista('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost')

CSRF_TRUSTED_ORIGINS = _env_lista(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'http://127.0.0.1,http://localhost',
)


# Application definition

INSTALLED_APPS = [
    'core.apps.CoreConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'helpdesk',
    'chips',
    'emails',
    'equipment',
    'operadores',
    'discador.apps.DiscadorConfig',
    'integracoes.apps.IntegracoesConfig',
    'mcp_api.apps.McpApiConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Grava último 500 em logs/last_500.txt (diagnóstico produção)
    'core.middleware.CaptureLast500Middleware',
]

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.modulos_menu',
                'core.context_processors.wizard_gestor',
                'helpdesk.context_processors.helpdesk_permissoes',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_db_engine = os.environ.get('DB_ENGINE', 'sqlite3').lower()


def _postgres_options() -> dict:
    """Opções extras do driver psycopg (SSL, etc.)."""
    opcoes = {}
    sslmode = os.environ.get('DB_SSLMODE', '').strip()
    if sslmode:
        opcoes['sslmode'] = sslmode
    return opcoes


def _conn_max_age() -> int:
    bruto = os.environ.get('DB_CONN_MAX_AGE', '0').strip()
    try:
        return max(0, int(bruto))
    except ValueError:
        return 0


if _db_engine == 'postgresql':
    _pg_password = os.environ.get('DB_PASSWORD', '')
    if not DEBUG and not _pg_password:
        raise ImproperlyConfigured(
            'Com DB_ENGINE=postgresql e DJANGO_DEBUG=False, defina DB_PASSWORD no .env.'
        )

    _pg_config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'crm_ti'),
        'USER': os.environ.get('DB_USER', 'crm_ti'),
        'PASSWORD': _pg_password,
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'CONN_MAX_AGE': _conn_max_age(),
    }
    _pg_options = _postgres_options()
    if _pg_options:
        _pg_config['OPTIONS'] = _pg_options

    DATABASES = {'default': _pg_config}
elif _db_engine == 'mysql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DB_NAME', 'crm_ti'),
            'USER': os.environ.get('DB_USER', 'root'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DB_PORT', '3306'),
        }
    }
else:
    _sqlite_name = os.environ.get('DB_NAME', 'db.sqlite3')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / _sqlite_name,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = os.environ.get('DJANGO_LANGUAGE_CODE', 'pt-br')

TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'America/Sao_Paulo')

USE_I18N = True

USE_TZ = True


def _normalizar_static_url(url: str) -> str:
    """Garante URL absoluta (/static/) para o admin não gerar caminhos sob /admin/login/."""
    url = (url or '/static/').strip()
    if not url.startswith('/'):
        url = f'/{url}'
    if not url.endswith('/'):
        url = f'{url}/'
    return url


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Barra inicial obrigatória: sem ela o admin gera URLs relativas (/admin/login/static/...)
# e o Django trata esses caminhos como rotas do admin → 403 para usuários sem is_staff.
STATIC_URL = _normalizar_static_url(os.environ.get('DJANGO_STATIC_URL', '/static/'))
STATIC_ROOT = BASE_DIR / os.environ.get('DJANGO_STATIC_ROOT', 'staticfiles')

# Custom User Model
AUTH_USER_MODEL = 'core.CustomUser'

# Auth settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
SISTEMA_URL_PUBLICA = os.environ.get('SISTEMA_URL_PUBLICA', 'https://ti.moneypromotora.com.br/').rstrip('/') + '/'
# Token Bearer para API MCP (somente leitura). Sem token → endpoints retornam 503.
MCP_API_TOKEN = (os.environ.get('MCP_API_TOKEN') or '').strip()

# Wizard flutuante de gestão (DeepSeek + tools). Default: só o user id 2.
def _ids_inteiros(nome: str, padrao: list[int]) -> list[int]:
    bruto = os.environ.get(nome)
    if not bruto:
        return list(padrao)
    ids = []
    for item in bruto.split(','):
        item = item.strip()
        if item.isdigit():
            ids.append(int(item))
    return ids or list(padrao)


GESTOR_WIZARD_USER_IDS = _ids_inteiros('GESTOR_WIZARD_USER_IDS', [2])

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Web Push (helpdesk) — gere chaves com: python -m py_vapid --applicationServerKey
def _carregar_vapid_private_key(valor: str) -> str:
    """Aceita conteúdo PEM ou caminho para arquivo .pem na VPS."""
    valor = (valor or '').strip()
    if not valor:
        return ''
    caminho = Path(valor)
    if caminho.is_file():
        return caminho.read_text(encoding='utf-8').strip()
    return valor


VAPID_PUBLIC_KEY = os.environ.get('VAPID_PUBLIC_KEY', '').strip()
VAPID_PRIVATE_KEY = _carregar_vapid_private_key(os.environ.get('VAPID_PRIVATE_KEY', ''))
VAPID_ADMIN_EMAIL = os.environ.get('VAPID_ADMIN_EMAIL', 'mailto:ti@localhost')

# Cache-busting do frontend helpdesk (?v=) — automático via hash do commit git
from helpdesk.version import resolver_versao_frontend  # noqa: E402
HELPDESK_FRONTEND_VERSION = resolver_versao_frontend(BASE_DIR)

# Evitar migrações indesejadas de chaves primárias
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
